#!/bin/bash

# OSINT Café - Hackathon Perks Activation Guide
# Activate these perks to supercharge your cybersecurity platform!

echo "🎯 OSINT Café - Hackathon Perks Activation"
echo "=========================================="
echo ""

echo "🔥 PERKS STATUS CHECK - OSINT Café Project"
echo "1. ElevenLabs Creator Tier (Voice AI)"
echo "   ✅ PERK ACTIVATED"
echo "   🔧 ACTION: Create new API key for 'OSINT Café' project"
echo "   → Go to: https://elevenlabs.io/app/speech-synthesis"
echo "   → Create new project: 'OSINT Café'"
echo "   → Generate new API key"
echo "   → Benefit: 100k credits/month active"
echo ""

echo "2. Algorand/IPFS API (Blockchain)"
echo "   ✅ PERK ACTIVATED"
echo "   ✅ CAN KEEP EXISTING: API keys work regardless of project name"
echo "   → Current setup is fine - no changes needed"
echo "   → Benefit: \$512 value active"
echo ""

echo "3. Tavus (AI Avatar)"
echo "   ✅ PERK ACTIVATED"
echo "   🔧 ACTION: Create new avatar for 'OSINT Café'"
echo "   → Go to: https://studio.tavus.io"
echo "   → Create new avatar: 'OSINT Café Cybersecurity Expert'"
echo "   → API key should work across projects"
echo "   → Benefit: \$150 credits active"
echo ""

echo "🚀 SECONDARY PERKS STATUS"
echo "4. Sentry (Monitoring)"
echo "   ✅ PERK ACTIVATED"
echo "   🔧 ACTION: Create new project for 'OSINT Café'"
echo "   → Go to: https://sentry.io/organizations/your-org/projects/"
echo "   → Create new project: 'OSINT Café'"
echo "   → Update DSN in .env file"
echo "   → Benefit: 6 months Team Plan active"
echo ""

echo "5. Pica Pro (Image Processing)"
echo "   ✅ PERK ACTIVATED"
echo "   ✅ CAN KEEP EXISTING: API keys work across projects"
echo "   → Current API key works fine"
echo "   → Benefit: 2 months free active"
echo ""

echo "6. Dappier (AI Data)"
echo "   ✅ PERK ACTIVATED"
echo "   ✅ CAN KEEP EXISTING: API keys work across projects"
echo "   → Current setup is fine"
echo "   → Benefit: \$25 credits + 50% off active"
echo ""

echo "💡 REBRANDING STRATEGY FOR OSINT CAFÉ:"
echo "🔧 NEED NEW API KEYS (Project-Specific):"
echo "  • ElevenLabs - Create 'OSINT Café' voice models"
echo "  • Sentry - Create 'OSINT Café' monitoring project"
echo "  • Tavus - Create 'OSINT Café Cybersecurity Expert' avatar"
echo ""
echo "✅ KEEP EXISTING API KEYS (Project-Agnostic):"
echo "  • Algorand/IPFS - Blockchain APIs work universally"
echo "  • Pica Pro - Image processing APIs work universally"
echo "  • Dappier - AI data APIs work universally"
echo "  • Most other APIs in your .env file"
echo ""
echo "🎯 PRIORITY ACTIONS:"
echo "1. Test current APIs - most should work fine!"
echo "2. Create new ElevenLabs voice for 'OSINT Café Assistant'"
echo "3. Create new Sentry project for proper monitoring"
echo "4. Create Tavus avatar as 'Cybersecurity Expert'"
echo ""
echo "✅ YOUR .ENV FILE IS READY - TEST FIRST, THEN UPDATE!"
echo "🎉 All activated perks are working - just need proper branding!"
