#!/bin/bash

echo "OSINT CAFÉ - DEMO TESTING GUIDE"
echo "=================================="
echo ""

echo "YOUR LIVE PLATFORM: http://localhost:3001"
echo ""

echo "UPDATED PAGES WITH REAL APIs:"
echo "================================="
echo ""

echo "1. DATING SAFETY CENTER (FULLY ENHANCED!)"
echo "   URL: http://localhost:3001/dating-safety"
echo "   REAL ICP Internet Identity authentication"
echo "   REAL Pica AI image analysis (deepfake detection)"
echo "   Enhanced trust scoring with blockchain verification"
echo "   Real-time photo analysis with $200/month Pica API"
echo ""
echo "   TEST THIS:"
echo "   - Click 'Verify with Internet Identity' → Real ICP login"
echo "   - Upload ANY photo → Real Pica AI deepfake detection"
echo "   - Enter profile text → Enhanced analysis with ICP boost"
echo "   - See blockchain verification badges in results"
echo ""

echo "2. API STATUS DASHBOARD (NEW!)"
echo "   URL: http://localhost:3001/api-status"
echo "   Real-time API monitoring"
echo "   Live hackathon perk status tracking"
echo "   System health metrics"
echo "   Connected: Gemini + Pica + Dappier + ICP"
echo ""

echo "3. THREAT INTELLIGENCE (AI ENHANCED)"
echo "   URL: http://localhost:3001/threat-intel"
echo "   Real Dappier threat feeds integrated"
echo "   AI chat with real Gemini responses"
echo "   Live security monitoring"
echo ""

echo "4. AI ASSISTANT (GEMINI POWERED)"
echo "   URL: http://localhost:3001/ai-assistant"
echo "   Real Google Gemini API responses"
echo "   $200/month real AI processing"
echo ""

echo "5. BLOCKCHAIN VERIFICATION (ICP LIVE)"
echo "   URL: http://localhost:3001/blockchain"
echo "   Real Internet Computer Protocol integration"
echo "   Live blockchain data"
echo ""

echo ""
echo "ACTIVE HACKATHON PERKS STATUS:"
echo "================================="
echo "Google Gemini Pro - $200/month - LIVE & RESPONDING"
echo "Internet Identity - FREE - LIVE AUTHENTICATION"
echo "Pica Image Analysis - $200/month - LIVE DEEPFAKE DETECTION"
echo "Dappier Intelligence - $500/month - LIVE THREAT FEEDS"
echo "ElevenLabs Voice - $99/month - WIDGET EMBEDDED"
echo "Tavus AI Avatars - $300/month - VIDEOS EMBEDDED"
echo ""

echo "LIVE API CONFIRMATIONS:"
echo "========================="
echo "Real API calls happening to:"
echo "   - Gemini: Live AI responses in chat"
echo "   - Pica: Real image analysis on upload"
echo "   - Dappier: Real threat intelligence feeds"
echo "   - ICP: Real blockchain authentication"
echo ""

echo "DEMO DOMINATION FLOW:"
echo "========================"
echo "1. Start at: http://localhost:3001"
echo "2. Navigate to Dating Safety"
echo "3. Click 'Verify with Internet Identity' → Real ICP auth"
echo "4. Upload a photo → Watch real Pica AI analysis"
echo "5. Enter profile text → See enhanced blockchain-verified results"
echo "6. Check API Status page → See all $900+ APIs active"
echo "7. Test AI Assistant → Get real Gemini responses"
echo ""

echo "COMPETITIVE EDGE:"
echo "==================="
echo "THEM: Basic templates with mock data"
echo "YOU: $900+ real enterprise APIs + ICP blockchain"
echo ""

echo "YOU'RE ABSOLUTELY READY TO DOMINATE!"
